### ISSUE TITLE
1.21への対応

### ISSUE THREAD

**Issue by vermilion6** [CIB-MC/CIBPlugin#1]
バージョン1.21.1で このプラグインを使用する事ができなくなりました。
新バージョンへの対応はありますか？

**Comment by CIB-MC** [comment]
ご連絡をいただきましてありがとうございます。
対応可能かどうか確認の上、修正版をリリースさせていただければと思います。

※ サポートにつきましては、弊HPで配布のものに限らせていただいております。
　 その他の条件も含めまして、予めご了承ください。
　 [https://rainyvillage.jp/blog/333/](https://rainyvillage.jp/blog/333/)

**Comment by CIB-MC** [comment]
@vermilion6 様
当方でPaperMC 1.21.1での動作を確認いたしましたが、問題はございませんでした。
お手数ではございますがプラグインサーバープログラムの種別(SpigotMC/PaperMC)などをお伺いしてもよろしいでしょうか。
また、具体的に使用できないとする事象の詳細について併せて情報をご提供ください。

**Comment by vermilion6** [comment]
@CIB-MC 様
ご確認ありがとうございます。
改めてHPから正しいプラグインをダウンロードして確認したところ
PaperMC1.21.1の私の環境でも
正常に使用できることを確認できました。

私が元々使用していたプラグインがフォーク先の物を利用しており
使用する際 内部のファイルが重複しており
サーバー起動時にプラグインが読み込まないのが原因でした。
ご確認のお手数をおかけして申し訳ありませんでした。

良いプラグインを作って頂きありがとうございました
これからも使用させていただきたいと思います。
